### ISSUE TITLE
Unable to Create Models

### ISSUE THREAD

**Issue by sofiajonsson** [learn-co-curriculum/activerecord-yelp-exercises#1]
Tried to create models by running:
 `rails g model tag name:string` and 
`rails g resource tags name:string` 

Was met with error message:
-Usage list
-Options list
-Runtime options
-Rails options
-Description
-`Example:
    rails new ~/Code/Ruby/weblog`

Can create relationships between models after runing `rails new yelp` in terminal, so the issue lies in the learn lab, not my computer.

**Comment by rrcobb** [comment]
Hi Sofia! Thanks for adding an issue! 

This isn't a rails app, so the rails generators won't work. It does include the sinatra activerecord rake tasks, so if you want to generate migrations you can use

```
rake db:create_migration NAME=create_tags
```

If you'd like to use the rails generators, you can do the exercises in a new rails project - just copy the tests over.

**Comment by sofiajonsson** [comment]
Hi Robert,

Thanks for the response! The basic rake commands aren't working and my
teacher's aren't sure what else is wrong. I attached an example of pulling
up the console which produced this error message:

/ ♥rake console
rake aborted!
LoadError: cannot load such file -- sinatra/activerecord
/Users/sofiajonsson/dev/mod_redo/activerecord-yelp-exercises-seattle-web-career-021819/config/environment.rb:3:in
`require'
/Users/sofiajonsson/dev/mod_redo/activerecord-yelp-exercises-seattle-web-career-021819/config/environment.rb:3:in
`<top (req
uired)>'
/Users/sofiajonsson/dev/mod_redo/activerecord-yelp-exercises-seattle-web-career-021819/Rakefile:1:in
`require_relative'
/Users/sofiajonsson/dev/mod_redo/activerecord-yelp-exercises-seattle-web-career-021819/Rakefile:1:in
`<top (required)>'
/Users/sofiajonsson/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in
`eval'
/Users/sofiajonsson/.rvm/gems/ruby-2.6.1/bin/ruby_executable_hooks:24:in
`<main>'
(See full trace by running task with --trace)


Just wanted to pass it along.

Thanks!

Sofia
